### ISSUE TITLE
Revise Add-NewLink -Force to allow overwriting existing links

### ISSUE THREAD

**Issue by joeltimothyoh** [theohbrothers/ItemLinkManagement#10]
If `-Force` is specified, existing links regardless of type should be allowed to be overwritten.

**Comment by joeltimothyoh** [comment]
If this is to be implemented, #6 will need to be updated to accommodate the change.  @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh what happens if the existing item is a file / directory?

**Comment by joeltimothyoh** [comment]
> @joeltimothyoh what happens if the existing item is a file / directory?

@leojonathanoh The parameters would simply be passed to `New-Item` for direct invocation: https://github.com/theohbrothers/ItemLinkManagement/blob/0d9d8ad85696563d077339526e35d53838ea07c4/src/ItemLinkManagement/Public/New-ItemLink.ps1#L46
